### ISSUE TITLE
rot_axes and plot_rot_axes unsuccessful

### ISSUE THREAD

**Issue by OSUBUCKEYE1993** [bryanhanson/LearnPCA#16]
Dear sir,

I have not been able to run the code of the vignette n°4 scores and loading,
the rot_axes and the plot_rot_axes are unknown by any of   the R Package that I know or of the R packages launched thru you code

Best regards

**Comment by bryanhanson** [comment]
If you are running everything from scratch, you can get all the code [here](https://cran.r-project.org/web/packages/LearnPCA/index.html) (use the source code link).  The functions you are looking for are in the vignettes directory.
